### ISSUE TITLE
ios不兼容的吗

### ISSUE THREAD

**Issue by CCGui** [huajianduzhuo/vueConfig#2]

**Comment by huajianduzhuo** [comment]
长按事件吗？兼容IOS的。用的定时器，不会有兼容问题

**Comment by CCGui** [comment]
> 长按事件吗？兼容IOS的。用的定时器，不会有兼容问题

对呀 所以很纳闷在H5中ios居然没有响应，在chrome和安卓机都可以

**Comment by CCGui** [comment]
是代码第59行就挂了 所以没有响应 知道什么问题吗

**Comment by huajianduzhuo** [comment]
我用iPhone的Safari浏览器是没问题的，你那是iOS的什么环境？app还是浏览器？

**Comment by CCGui** [comment]
> 我用iPhone的Safari浏览器是没问题的，你那是iOS的什么环境？app还是浏览器？

我也是使用Safari浏览器。很纳闷

**Comment by CCGui** [comment]
已经解决了谢谢

**Comment by huajianduzhuo** [comment]
> 已经解决了谢谢

可以说下是什么问题吗？
